apiVersion: apps/v1
kind: Deployment
metadata:
  name: eew
  labels:
    {{- include "eew-chart.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "eew-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "eew-chart.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: eew-sa
      tolerations:
{{ .Values.tolerations | toYaml | indent 8 }}
      containers:
        - name: eew
          image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["-interval","{{ .Values.args.interval }}","-list","{{ .Values.args.list }}"]
{{- if .Values.nodeSelector }}
      nodeSelector: {{- .Values.nodeSelector | toYaml | nindent 8 }}
{{- end }}
